# Site basics
title: Your Name
description: PhD Candidate | Structural Eng, Risk & Reliability, Structural Health Monitoring.
url: "https://AliAmeri75.github.io"
baseurl: ""              # exactly empty for a personal site
github_username: "AliAmeri75"

# Use GitHub’s Minimal theme via remote_theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional simple nav (these filenames must exist)
header_pages:
  - publications.md
  - projects.md
  - contact.md

  
